import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import { Lato } from "next/font/google";
import { Bayon } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { CartProvider } from "@/Context/CartContext";
import Providers from "./Providers";
import CartDrawer from "@/Components/GlobalUi/Cart/CartDrawer";

const bayon = Bayon({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bayon",
});

const lato = Lato({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-lato",
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${lato.variable} ${bayon.variable} `}
      >
        <Providers>
          <Header />
          <CartDrawer />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
