import AppLayout from "@/app/AppLayout";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import { Lato } from "next/font/google";
import { Bayon } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "react-loading-skeleton/dist/skeleton.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const lato = Lato({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-lato",
});

const bayon = Bayon({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bayon",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${lato.variable} ${bayon.variable}`}
      >
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
